version: '3.8'

services:
  filebeat:
    build:
      context: filebeat/
      args:
        FILEBEAT_VERSION: 7.11.0 
    volumes:
    - ./dataCsv:/tmp/dataCsv/*.csv 
    - type: bind
      source: ./filebeat/config/filebeat.yml
      target: /usr/share/filebeat/filebeat.yml
      read_only: true
    ports:
      - "5044:5044"
    command: ["--strict.perms=false"]
    depends_on:
    - logstash
    - elasticsearch
      #- kibana
    networks:
    - elk

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.10.1
    volumes:
    - type: bind
      source: ./elasticsearch/config/elasticsearch.yml
      target: /usr/share/elasticsearch/config/elasticsearch.yml
      read_only: true
    - type: volume
      source: elasticsearch
      target: /usr/share/elasticsearch/data
    restart: always
    ipc: host
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        #ELASTIC_PASSWORD: letmein
      discovery.type: single-node
    networks:
    - elk

      #kibana:
      #build:
      #context: kibana/
      #args:
      #  ELK_VERSION: $ELK_VERSION
      #volumes:
      #- type: bind
      #source: ./kibana/config/kibana.yml
      #target: /usr/share/kibana/config/kibana.yml
      #read_only: true
      #restart: always
      #ports:
      #- "5601:5601"
      #networks:
      #- elk
      #depends_on:
      #- elasticsearch

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.10.1
    volumes:
    - type: bind
      source: ./logstash/config/logstash.yml
      target: /usr/share/logstash/config/logstash.yml
      read_only: true
    - type: bind
      source: ./logstash/pipeline
      target: /usr/share/logstash/pipeline
      read_only: true
    ipc: host
    restart: always
    ports:
    - "5000:5000"
    - "9600:9600"  
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - elk
    depends_on:
    - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
